"""Task Description #1: Classes (Student Class)
Scenario
You are developing a simple student information management module.
Task
• Use an AI tool (GitHub Copilot / Cursor AI / Gemini) to complete a Student class.
• The class should include attributes such as name, roll number, and branch.
• Add a method display_details() to print student information.
• Execute the code and verify the output.
• Analyze the code generated by the AI tool for correctness and clarity.
Expected Output #1
• A Python class with a constructor (__init__) and a display_details() method.
• Sample object creation and output displayed on the console.
• Brief analysis of AI-generated code.
class Student:
    def __init__(self, name, roll_number, branch):
        self.name = name
        self.roll_number = roll_number
        self.branch = branch
    def display_details(self):
        print(f"Name: {self.name}")
        print(f"Roll Number: {self.roll_number}")
        print(f"Branch: {self.branch}")
# Sample object creation
student1 = Student("Alice", "101", "Computer Science")  
student2 = Student("Bob", "102", "Mechanical Engineering")
# Displaying student details
student1.display_details()
student2.display_details()

# Analysis of AI-generated code
# The AI-generated code correctly defines a Student class with the required attributes and methods.
# The __init__ method initializes the attributes name, roll_number, and branch.
# The display_details() method effectively prints the student's information in a clear format.  
# The sample object creation and method calls demonstrate the functionality of the class as intended."""

"""#Task Description #2: Loops (Multiples of a Number)
Scenario
You are writing a utility function to display multiples of a given number.
Task
• Prompt the AI tool to generate a function that prints the first 10 multiples of a given number
using a loop.
• Analyze the generated loop logic.
• Ask the AI to generate the same functionality using another controlled looping structure (e.g.,
while instead of for).
Expected Output #2
• Correct loop-based Python implementation.
• Output showing the first 10 multiples of a number.
• Comparison and analysis of different looping approaches.

def print_multiples_for(number):
    for i in range(1, 11):
        print(f"{number} x {i} = {number * i}")
def print_multiples_while(number):
    i = 1
    while i <= 10:
        print(f"{number} x {i} = {number * i}")
        i += 1
# Using the for loop function
print("Multiples using for loop:")
print_multiples_for(5)
# Using the while loop function
print("\nMultiples using while loop:")
print_multiples_while(5)

# Analysis of generated code
# The for loop implementation iterates from 1 to 10, multiplying the input number by the loop index.
# The while loop implementation achieves the same result by initializing a counter and incrementing it until it reaches 10.
# Both implementations correctly print the first 10 multiples of the given number, demonstrating different looping constructs effectively.  """

"""ask Description #3: Conditional Statements (Age Classification)
Scenario
You are building a basic classification system based on age.
Task
• Ask the AI tool to generate nested if-elif-else conditional statements to classify age groups
(e.g., child, teenager, adult, senior).
• Analyze the generated conditions and logic.
• Ask the AI to generate the same classification using alternative conditional structures (e.g.,
simplified conditions or dictionary-based logic).
Expected Output #3
• A Python function that classifies age into appropriate groups.
• Clear and correct conditional logic.
• Explanation of how the conditions work.      
def classify_age_nested(age):
    if age < 13:
        return "Child"
    elif 13 <= age < 20:
        return "Teenager"
    elif 20 <= age < 60:
        return "Adult"
    else:
        return "Senior" 
def classify_age_dict(age):
    age_groups = {
        range(0, 13): "Child",
        range(13, 20): "Teenager",
        range(20, 60): "Adult",
        range(60, 150): "Senior"
    }
    for age_range, group in age_groups.items():
        if age in age_range:
            return group
    return "Unknown"
# Testing the functions
ages = [5, 15, 25, 65]
print("Using nested if-elif-else:")
for age in ages:
    print(f"Age: {age} - Group: {classify_age_nested(age)}")
print("\nUsing dictionary-based logic:")
for age in ages:
    print(f"Age: {age} - Group: {classify_age_dict(age)}")  
# Analysis of generated code
# The nested if-elif-else function checks the age against defined ranges to classify it into groups.
# The dictionary-based function uses ranges as keys and iterates through them to find the appropriate group.
# Both methods effectively classify ages, with the nested approach being more straightforward and the dictionary approach offering flexibility for future modifications. """

  
"""Task Description #4: For and While Loops (Sum of First n Numbers)
Scenario
You need to calculate the sum of the first n natural numbers.
Task
• Use AI assistance to generate a sum_to_n() function using a for loop.
• Analyze the generated code.
• Ask the AI to suggest an alternative implementation using a while loop or a mathematical
formula.
Expected Output #4
• Python function to compute the sum of first n numbers.
• Correct output for sample inputs.
• Explanation and comparison of different approaches."""

"""def sum_to_n_for(n):
    total = 0
    for i in range(1, n + 1):
        total += i
    return total    
def sum_to_n_while(n):
    total = 0
    i = 1
    while i <= n:
        total += i
        i += 1
    return total
def sum_to_n_formula(n):
    return n * (n + 1) // 2

# Testing the functions
n = 10  
print(f"Sum of first {n} numbers using for loop: {sum_to_n_for(n)}")
print(f"Sum of first {n} numbers using while loop: {sum_to_n_while(n)}")
print(f"Sum of first {n} numbers using formula: {sum_to_n_formula(n)}")
# Analysis of generated code
# The for loop implementation iterates through numbers from 1 to n, accumulating the sum.   
# The while loop implementation achieves the same result by using a counter that increments until it reaches n.
# The formula-based implementation provides a direct mathematical calculation, which is the most efficient.
# All three methods correctly compute the sum of the first n natural numbers, with varying levels of efficiency and complexity."""


"""Generate a Python BankAccount class with methods deposit(), withdraw(), and check_balance(), including comments, sample usage, and explanation of how the class works."""
class BankAccount:
    def __init__(self, account_holder, initial_balance=0):
        """Initialize the bank account with account holder's name and an optional initial balance."""
        self.account_holder = account_holder
        self.balance = initial_balance

    def deposit(self, amount):
        """Deposit a specified amount into the account."""
        if amount > 0:
            self.balance += amount
            print(f"Deposited: ${amount:.2f}")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        """Withdraw a specified amount from the account if sufficient funds are available."""
        if amount > 0:
            if amount <= self.balance:
                self.balance -= amount
                print(f"Withdrew: ${amount:.2f}")
            else:
                print("Insufficient funds for this withdrawal.")
        else:
            print("Withdrawal amount must be positive.")

    def check_balance(self):
        """Check and return the current balance of the account."""
        print(f"Current balance: ${self.balance:.2f}")
        return self.balance 
# Sample usage
account = BankAccount("John Doe", 1000) 
account.check_balance()  # Check initial balance
account.deposit(500)     # Deposit money
account.withdraw(200)    # Withdraw money
account.check_balance()  # Check balance after transactions
# Explanation of how the class works
# The BankAccount class represents a simple bank account with methods to deposit, withdraw, and check

# the balance. The __init__ method initializes the account with the account holder's name and an optional initial balance.
# The deposit() method allows adding funds to the account, while the withdraw() method checks for sufficient funds before allowing a withdrawal.
# The check_balance() method displays the current balance. Sample usage demonstrates creating an account and performing various transactions.   
